### ISSUE TITLE
Nieuwe versie van /corona-check/token nog niet valide i.c.m. JSON data structures

### ISSUE THREAD

**Issue by falko100** [minvws/nl-covid19-coronacheck-provider-docs#11]
Nieuwe versie doet het inderdaad beter, maar nog niet volledig correct.
Datum van test token 8T528T528T52 is 1945-05-12T00:00:00.
Ook expected datum format nog niet correct.

<img width="837" alt="Schermafbeelding 2021-07-03 om 16 30 31" src="https://user-images.githubusercontent.com/11974977/124357576-8a27ef00-dc1c-11eb-97a7-387cc7705a44.png">

Kon #7 niet heropenen, dus vandaar nieuwe ticket.

**Comment by reincode050** [comment]
👍. Dank voor het checken en melden overigens!!

**Comment by reincode050** [comment]
<img width="394" alt="Screenshot 2021-07-03 at 19 15 35" src="https://user-images.githubusercontent.com/84009181/124362065-180ed480-dc33-11eb-90e2-e98da122b005.png">

De code is eenvoudig, dus nu wordt het interessant. Want dit betekent dat we in onze eigen database de datum verkeerd hebben ingeladen (als 5 december 1945). Het moet 12 mei 1945 zijn uiteraard.

En dit ga ik dus controleren voor alle records. Ik trek dit issue dus wat groter.

**Comment by reincode050** [comment]
De database wijziging wordt volgens mij nu (of zodirect) uitgerold op productie

**Comment by falko100** [comment]
Geboortedatum format gaat nu goed.
`sampleDate` is nog steeds niet volgens documentatie.

**Comment by falko100** [comment]
Ik zie een close maar geen reactie. Is dit inmiddels opgelost?

**Comment by reincode050** [comment]
Falko, klopt. ik sloot het verkeerde issue afgelopen week, ik heb hem dan ook weer geopend.
Ik ben bezig met een stukje code die de geboortedatum beschouwd als een string en niet als een datum. Daar zit een denk-/design fout die ik wil oplossen om dit issue te kunnen sluiten.

De geboortedatum op een paspoort kan tenminste de volgende officiële varianten bevatten en zodoende moet het worden gecontroleerd op vorm en niet of het een (technisch) valide datum is:
- 1971-10-22
- 1971-10-00
- 1971-00-00
- 1971-00
- 1971-XX-01
- 1971-XX-XX
