### ISSUE TITLE
Absolute data inconsistentie in data structuur, test data en https://provider.coronacheck.nl/corona-check/token

### ISSUE THREAD

**Issue by falko100** [minvws/nl-covid19-coronacheck-provider-docs#7]
Data structures (https://github.com/minvws/nl-covid19-coronacheck-provider-docs/blob/main/docs/data-structures-overview.md)
Test suite data (https://github.com/minvws/nl-covid19-coronacheck-provider-docs/blob/main/test-suite/default-test-cases-v3.csv)
CoronaCheck Token test tool (https://provider.coronacheck.nl/corona-check/token)

Zijn compleet inconsistent.
Linker data komt groot en deels uit de test csv. Rechter data is de expected data.
![image](https://user-images.githubusercontent.com/11974977/123799470-8d537000-d8e8-11eb-8f38-7fc892e824a9.png)

**Comment by reincode050** [comment]
Beste Falko, dit is bekend. We verwachten dit vandaag in de testtool te verbeteren zodat de kolom 'Expected' de juiste gegevens toont en 100% overeenkomt met de test_cases CSV file

**Comment by falko100** [comment]
Top bedankt.
Daarnaast staat in de documentatie dat de PKI-O voldoen moet aan het G3 certificaat. Echter staat op de website van Logius dat G1 per 31-12-2020 G3 moet vervangen.

**Comment by nicktencate** [comment]
`Staat der Nederlanden Root CA - G3` is geldig tot 2028-11-14.

https://www.pkioverheid.nl/

Wellicht hebben ze het over een ander certificaat?

**Comment by falko100** [comment]
> `Staat der Nederlanden Root CA - G3` is geldig tot 2028-11-14.
> 
> https://www.pkioverheid.nl/
> 
> Wellicht hebben ze het over een ander certificaat?

Klopt. Goed lezen is soms moeilijk 😅 
Thanks voor de snelle reactie op dit issue.

**Comment by falko100** [comment]
Hoe laat verwachten jullie het opgelost te hebben?

**Comment by reincode050** [comment]
We gaan uit van vannacht. Maar kan er niet 100% zeker over zijn. Hangt ook af van een aantal andere releases van andere onderdelen van de gehele keten.

**Comment by falko100** [comment]
Ik zie dat de nieuwe release gedaan is. Echter lijkt het nog niet allemaal te kloppen.
`manufacturer` en `name` staat bij ons hier niet goed, maar verder zou dit volgens mij moeten kloppen.

![image](https://user-images.githubusercontent.com/11974977/123934470-99483c00-d993-11eb-8413-752d4727116f.png)

**Comment by reincode050** [comment]
Je bent snel. Inderdaad is het ongeveer een uur geleden uitgerold en nu beter in sync.

**Comment by falko100** [comment]
Wel beter inderdaad, maar volgens mij niet goed in combinatie met de JSON data structuren?

**Comment by falko100** [comment]
Wat moet aangehouden worden? De https://provider.coronacheck.nl/corona-check/token test of de https://github.com/minvws/nl-covid19-coronacheck-provider-docs/blob/main/docs/data-structures-overview.md ?
Dit is absoluut niet duidelijk momenteel.

**Comment by reincode050** [comment]
De json van de documentatie.
Ik schrijf vanavond betere testtool code. Mijn fout :-(

**Comment by falko100** [comment]
Dag @reincode050,

Is dit inmiddels al gelukt?
Heb je een ETA voor mij?

**Comment by reincode050** [comment]
Dit is opgelost en in productie gezet

**Comment by falko100** [comment]
Nieuwe versie doet het inderdaad beter, maar nog niet volledig correct.
Datum van test token `8T528T528T52` is `1945-05-12T00:00:00`.
Ook expected datum format nog niet correct.

![image](https://user-images.githubusercontent.com/11974977/124357498-053cd580-dc1c-11eb-9228-bcde4bc1cc5e.png)

**Comment by reincode050** [comment]
Oh mijn excuus. Die is erin geslopen. Ik verbeter dit vanavond
