### ISSUE TITLE
Mogelijkheid tot testen met eigen token verdwenen

### ISSUE THREAD

**Issue by falko100** [minvws/nl-covid19-coronacheck-provider-docs#9]
Bij de testtool is het niet langer mogelijk om met eigen token te testen.
![image](https://user-images.githubusercontent.com/11974977/124351548-54264300-dbfb-11eb-8f20-1cf33ebdd6f5.png)

**Comment by reincode050** [comment]
Ook dit zit in dezelfde release. Planning zsm (ik hoop komende nacht)

**Comment by reincode050** [comment]
Dit is nu hersteld op productie
